version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "50003:50003"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000