name: sfa
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy==2.0.2
  - scipy==1.14.1
  - scikit-learn==1.5.2
  - ipython==8.28.0
  - librosa==0.10.2
  - pip:
    - fastapi==0.115.2
    - uvicorn==0.31.1
    - mido==1.3.2
    - partitura==1.5.0
    - pyaudio==0.2.14
    - midi2audio==0.1.1
    - pretty-midi==0.2.10
    - progressbar2==4.5.0
    - python-multipart==0.0.12
    - websockets==13.1
